ssg_accounts/urls.py
"""
URL configuration for the SSG Accounts application.

This module defines the URL patterns for the games application,
mapping URLs to views.
"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'ssg_accounts'

urlpatterns = [
    # User authentication views
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    # Password reset views
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='ssg_accounts/password_reset_form.html',
            email_template_name='ssg_accounts/password_reset_email.html',
            success_url='/accounts/password_reset/done/',
        ),
        name='password_reset',
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='ssg_accounts/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='ssg_accounts/password_reset_confirm.html'
        ),
        name='password_reset_confirm',
    ),
]

ssg_blog/urls.py
"""
URL configuration for the blog application.

This module defines the URL patterns for the blog application,
mapping URLs to views.
"""

from django.urls import path
from . import views

urlpatterns = [
    path('', views.Blog.as_view(), name='blog'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
]

ssg_config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('ssg_games.urls')),
    path('blog/', include('ssg_blog.urls')),
    path('contact/', include('ssg_contact.urls')),
    path('accounts/', include('ssg_accounts.urls', namespace='ssg_accounts')),
    path('socialaccounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('ssg_pages.urls')),

    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='ssg_accounts/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
]

templates/includes/footer.html
<!-- Footer start -->
<footer class="footer">
    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <p class="copy">© {% now 'Y' %} ScatterShot Games All Rights Reserved.</p>
                </div>
                <div class="col-lg-4">
                    <div class="social-list-2">
                        <!-- Social media links -->
                        <ul>
                            <li>
                                <a href="https://www.facebook.com/profile.php?id=100094130880081" target="_blank" class="facebook-bg" aria-label="www.facebook.com/profile.php?id=100094130880081"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="https://www.kickstarter.com/profile/scattershot-games/created?ref=nav_search&result=user&term=scattershot&total_hits=0" target="_blank" class="kickstarter-bg" aria-label="www.kickstarter.com/profile/scattershot-games"><i class="fa-brands fa-kickstarter"></i></a>
                            </li>
                            <li>
                                <a href="https://scattershot-games.itch.io/" target="_blank" class="itchio-bg" aria-label="scattershot-games.itch.io/"><i class="fa-brands fa-itch-io"></i></a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/scattershotgames/" target="_blank" class="instagram-bg" aria-label="www.instagram.com/scattershotgames"><i class="fa fa-instagram"></i></a>
                            </li>
                        </ul>
                        <!-- Social media links end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer end -->

templates/includes/messages.html
<!-- 
 
Message.html

Contains default message levels and tags for messages.

-->
{% if messages %} {% for message in messages %}
<div id="message" class="container">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong> {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error: {% else %} {{ message.tags|title }} {% endif %} </strong>
        {{ message }}
    </div>
</div>
{% endfor %} {% endif %}

templates/includes/nav_bar.html
{% load static %}


<!-- Main header start -->

<header class="main-header sticky-header header-with-top content-area-nav">
    <div class="container">
        <!-- Start of NavBar -->
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{% url 'home' %}">
                <i class="fa-solid fa-dice"></i>
                 ScatterShot Games
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="navbar">
                <ul class="navbar-nav ml-auto">
                    
                    <!-- Main Menu Links -->
                    <li class="nav-item">
                        <a 
                        {% if '/' == request.path %}
                        class="nav-link active"
                        {% else %} 
                        class="nav-link"
                        {% endif %}
                        href="{% url 'home' %}"><i class="fa-solid fa-house"></i>
                         Home
                        </a>
                    </li>

                    <li class='nav-item'>
                        <a                        
                        {% if request.resolver_match.url_name == 'games' %}
                        class="nav-link active"
                        {% else %} 
                        class="nav-link"
                        {% endif %}
                        href="{% url 'games' %}"><i class="fa-solid fa-chess-board"></i>
                         Games
                        </a>
                    </li>

                    <li class='nav-item'>
                        <a                        
                        {% if '/about' == request.path %}
                        class="nav-link active"
                        {% else %} 
                        class="nav-link"
                        {% endif %} 
                        href="{% url 'about' %}"><i class="fa-solid fa-circle-info"></i>
                         About
                        </a>
                    </li>

                    <li class='nav-item'>
                        <a                        
                        {% if request.resolver_match.url_name == 'blog' %}
                        class="nav-link active"
                        {% else %} 
                        class="nav-link"
                        {% endif %}
                        href="{% url 'blog' %}"><i class="fa-solid fa-blog"></i>
                         Blog
                        </a>
                    </li>

                    <li class='nav-item'>
                        <a                        
                        {% if request.resolver_match.url_name == 'contact' %}
                        class="nav-link active"
                        {% else %} 
                        class="nav-link"
                        {% endif %}
                        href="{% url 'contact' %}"><i class="fa-solid fa-message"></i>
                         Contact
                        </a>
                    </li>

                    <!-- User Login Links -->

                    <!-- Check is user authenticated, Show User Dashboard and logout links -->
                    {% if user.is_authenticated %}
                    <li class='nav-item'>
                        <a 
                        {% if '/accounts/dashboard/' == request.path %}
                        class="nav-link active sign-in"
                        {% else %} 
                        class="nav-link sign-in"
                        {% endif %} href="{% url 'ssg_accounts:dashboard' %}" class="sign-in nav-link"><i class="fa fa-user"></i> Dashboard</a>
                    </li>

                    <li class='nav-item'>
                        <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}" class="sign-out nav-link"><i class="fa fa-sign-out"></i> Logout</a>
                        <form action="{% url 'ssg_accounts:logout' %}" method="POST" id="logout">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                    </li>

                    <!-- Else: show login and signup links -->
                    {% else %}
                        <li class='nav-item'>
                        <a                        
                        {% if '/accounts/login/' == request.path %}
                        class="nav-link active sign-in"
                        {% else %} 
                        class="nav-link sign-in"
                        {% endif %} 
                        href="{% url 'ssg_accounts:login' %}"><i class="fa fa-sign-in"></i> Login</a>
                    </li>

                    <li class='nav-item'>
                        <a                        
                        {% if '/accounts/signup/' == request.path %}
                        class="nav-link active sign-in"
                        {% else %} 
                        class="nav-link sign-in"
                        {% endif %} 
                        href="{% url 'ssg_accounts:signup' %}"><i class="fa fa-user"></i> Register</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </nav>
        <!-- End of NavBar -->
    </div>
</header>
<!-- Main header end -->